/*
 * This file is part of StatusMCServerTool.
 *
 * StatusMCServerTool is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * StatusMCServerTool is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with StatusMCServerTool. If not, see <https://www.gnu.org/licenses/>.
 */
package com.devparada.frame;

import javax.swing.JOptionPane;

/**
 *
 * @author devparada
 */
public class AddServerDialog extends javax.swing.JDialog {

    private final InitFrame jFrame;

    /**
     * Saves the host and ip of dialog
     */
    private String HostIpDialog;

    /**
     * Creates new form AddServerDialog
     *
     * @param parent
     * @param modal
     */
    public AddServerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jFrame = (InitFrame) parent;
    }

    public String getHostIpDialog() {
        return HostIpDialog;
    }

    public void setHostIpDialog(String HostIpDialog) {
        this.HostIpDialog = HostIpDialog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblAdd = new javax.swing.JTextField();
        jTxtAdd = new javax.swing.JTextField();
        jBtnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Server");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jLblAdd.setEditable(false);
        jLblAdd.setBackground(new java.awt.Color(214, 217, 223));
        jLblAdd.setForeground(new java.awt.Color(0, 0, 0));
        jLblAdd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLblAdd.setText("Intraduce the server IP (with port if different)");
        jLblAdd.setBorder(null);

        jTxtAdd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtAdd.setText("myserverminecraft.ddns.net:24321");

        jBtnAdd.setBackground(new java.awt.Color(0, 204, 51));
        jBtnAdd.setText("Add server");
        jBtnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblAdd))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTxtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jBtnAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        this.setHostIpDialog(jTxtAdd.getText());

        if (checkAddDialog()) {
            String[] ipServerArray = getHostIpDialog().split(":");
            int port = 25565;

            String serverIp = getHostIpDialog();
            jTxtAdd.setText("");

            if (ipServerArray.length == 2) {
                port = Integer.parseInt(ipServerArray[1]);
            } else {
                serverIp = getHostIpDialog() + ":" + port;
            }

            this.setVisible(false);
            jFrame.database.addRow(serverIp);
            jFrame.addPanel(ipServerArray[0], port);
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_jBtnAddActionPerformed

    /**
     * Check the JTextField the dialog of dialog add server of the database
     *
     * @return Return true if checks are correct
     */
    private boolean checkAddDialog() {
        String JTxtText = getHostIpDialog();

        if (JTxtText.length() != 0) {
            String[] ipServerArray = JTxtText.split(":");

            // \\d+ -> only numbers 
            if (ipServerArray.length == 2 && !ipServerArray[1].matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "Port not is number", "Error Add Server", JOptionPane.WARNING_MESSAGE);
            } else if (ipServerArray.length == 2 && ipServerArray[1].matches("\\d+")) {
                return true;
            } else {
                return true;
            }
        } else {
            JOptionPane.showMessageDialog(this, "IP Server not blank", "Error Add Server", JOptionPane.WARNING_MESSAGE);
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddServerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddServerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddServerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddServerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AddServerDialog dialog = new AddServerDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JTextField jLblAdd;
    private javax.swing.JTextField jTxtAdd;
    // End of variables declaration//GEN-END:variables
}
